### ISSUE TITLE
mint.get_transactions() returns both income and expenses as positive numbers

### ISSUE THREAD

**Issue by Casyfill** [mrooney/mintapi#102]

**Comment by Casyfill** [comment]
`mint.get_detailed_transactions`, on the other hand, returns correct info

**Comment by mrooney** [comment]
Thanks for the report! This is a difference in how the underlying APIs work, and I don't want to make what would be a very backwards-incompatible change :) I believe the former does provide a "debit" or "credit" field to let you know if the amount is negative or positive. Just choose whichever you like and use appropriately.

**Comment by salmoni88** [comment]
Mike,

I would like to ask questions to your subscribers about the types of apps/tools they are working on and collaborate. 

What would be the most appropriate way to do this?  Is there a user group?

Mark

**Comment by mrooney** [comment]
@salmoni88 well, this random bug is definitely not the right place :) There is not a specific user group and there's no way to contact all users, alas. For any future communication, feel free to email me directly.
