### ISSUE TITLE
ius_session and thx_guid cookies

### ISSUE THREAD

**Issue by danepowell** [mrooney/mintapi#103]
The documentation says to retrieve these cookies by logging in to Mint manually and then copying the cookie values.

However, when I'm logged in to Mint, I don't see any cookies for intuit.com or mint.intuit.com matching the names "ius_session" or "thx_guid". Has Mint changed the names of these cookies?

**Comment by saltlakeryan** [comment]
I had a similar problem, but discovered that I needed to look for intuit cookies, not mint cookies (this is in the README, but easy to miss).  Here are some screenshots of me finding the cookies:
![ius_session](https://user-images.githubusercontent.com/1474660/28085487-203fda06-6639-11e7-827e-ee867948fd6f.png)
![thx_guid](https://user-images.githubusercontent.com/1474660/28085488-203fecd0-6639-11e7-81e8-79e999945cfd.png)

**Comment by saltlakeryan** [comment]
perhaps the readme could be updated from:

"visit chrome://settings/cookies and type intuit"
to:
"visit chrome://settings/cookies and type **intuit** (not mint)"

or something similar to add emphasis.  BTW, I find this method easier than using chromedriver.  I always run into problems with chromedriver.  Thanks for the handy library!

**Comment by mrooney** [comment]
README updated, thanks!
