### ISSUE TITLE
'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by musicmovesme** [mrooney/mintapi#105]
Getting this right after login:
Traceback (most recent call last):
  File "mintapi/api.py", line 769, in <module>
    main()
  File "mintapi/api.py", line 708, in main
    mint = Mint.create(email, password, ius_session=options.session, thx_guid=options.thx_guid)
  File "mintapi/api.py", line 74, in create
    mint.login_and_get_token(email, password, ius_session, thx_guid)
  File "mintapi/api.py", line 135, in login_and_get_token
    session_cookies = self.get_session_cookies(**data)
  File "mintapi/api.py", line 199, in get_session_cookies
    'ius_session': driver.get_cookie('ius_session')['value'],
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by dsinger51** [comment]
Same issue for me.

**Comment by dherg** [comment]
Looks like `driver.get_cookie()` isn't getting the cookies for ius_session or thx_guid. I think this has to do with the domains for ius_session and thx_guid being accounts.intuit.com and pf.intuit.com respectively, but `get_cookie()` is called while on the domain mint.intuit.com, so it only sees cookies with domains mint.intuit.com and .intuit.com.

A workaround to get ius_session is to accounts.intuit.com and get the cookie there:
`driver.get('http://accounts.intuit.com')`
`ius_session_cookie = driver.get_cookie('ius_session')['value']`

Doesn't seem to be as simple as going to pf.intuit.com to get the thx_guid cookie, however... not sure of a solution there.

**Comment by mrooney** [comment]
Thanks, fixed and released as 1.27!
