### ISSUE TITLE
Command-line script should return exit status 

### ISSUE THREAD

**Issue by felciano** [mrooney/mintapi#111]
It would be nice to be able to use the `mintapi` command line script to automate periodic downloads of data. In light of all the ways this can fail (especially around authentication) it would be nice to return a success/fail exit status to the shell. This would allow a shell script to monitor its success and trigger some sort of notification on failure (send an email, trigger a Growl notification, etc).

I'd be happy to contribute a patch if we can agree that its a good idea and on the desired behavior. I'm thinking something pretty simple: 0 on success, 1 on error. If we want to get fancy we could e.g. catch the "Challenge required" error and give it its own error code 2, etc.

**Comment by mrooney** [comment]
Seems reasonable! Though it should already be raising appropriate exceptions in these cases which should exit non-zero, right? Happy to accept a PR fixing any places that don't, just surprised it isn't already.

**Comment by felciano** [comment]
I didn't realize this. Let me test and confirm. What is supposed to happen if an exception is thrown -- do the details go to stderr and exit code to 1?

**Comment by mrooney** [comment]
Yes, that's what I'd expect

**Comment by felciano** [comment]
Works great, as is. Sorry for the noise
