### ISSUE TITLE
Looks like Mint cookies have changed

### ISSUE THREAD

**Issue by dzg** [mrooney/mintapi#119]
I just re-logged into Mint to reset my cookies, and I do not see `accounts.intuit.com` or `pf.intuit.com` in Cookies at all.

And no `ius_session` or `thx_guid` cookies anywhere. (The only 'session' type cookie I see is `MINTJSESSIONID` from `mint.intuit.com`)

Is it just me? Or does this API need rewriting now?

I hope that @mrooney has time to look into this!

**Comment by mrooney** [comment]
Unfortunately I don't have time to look into this :/ There are other issues for the recent changes, see #118 among other recent ones.
