### ISSUE TITLE
Transaction Updating 

### ISSUE THREAD

**Issue by Andreilys** [mrooney/mintapi#121]
I'm trying to pull my daily/weekly spend, however, mint.com doesn't actually load your transactions until you've logged into the website and let it load itself.

Is there any workaround for this? I'd rather not have to login each day just for the transactions to load, would running a selenium script that logs in for you at a specific time each day be a potential solution?

I tried to sleep for 600 seconds and it still didn't refresh until I actually logged in myself online.

```
                self.mint = mintapi.Mint(MINT_DETAILS[0], MINT_DETAILS[1], MINT_DETAILS[2], MINT_DETAILS[3])
                print("Sleeping")
                time.sleep(600)
                print("finished sleeping")
```
Any other recommendations on refreshing it programmatically?

**Comment by mrooney** [comment]
Please just comment on existing issues and/or remind me, instead of creating exactly the same issue again :) #113
