### ISSUE TITLE
Changes to the api

### ISSUE THREAD

**Issue by jorythompson** [mrooney/mintapi#130]
I am finally getting around to using the latest (selinium) version of mintapi.  I am happy to see this as I just recently started using selenium on other projects.

I found an issue with the api.py where parse_float() is referenced as a class method but it is just a function.  I'd also like to add a headless option to get_web_driver() so that you can run your app on a headless server (or if you just don't want to see the browser pop up.)

Never having contributed to github (other than my own repos) what is the appropriate way to do this?  Should I just push the changes up?

thanks in advance,
Jordan

**Comment by mrooney** [comment]
Thanks, that would be great! Please fork the repository and submit a Pull Request :) https://gist.github.com/Chaser324/ce0505fbed06b947d962
