### ISSUE TITLE
Support for Headless mode 

### ISSUE THREAD

**Issue by SterlingButters** [mrooney/mintapi#136]
I would like to run the mintAPI in my python code but without the Chrome GUI. 

I tried adding the following at line 176 in api.py:

```
from selenium import webdriver
options = webdriver.chrome.options.Options()
options.add_argument('--headless')
options.add_argument('--disable-gpu')
driver = webdriver.Chrome(chrome_options=options)
```

but it appears that the following code depends on the GUI because it just hangs. Is there any way around this?

**Comment by dzg** [comment]
How did you get this to work? I copied your code at 176

```
    def login_and_get_token(self, email, password):
        from selenium import webdriver
        options = webdriver.chrome.options.Options()
        options.add_argument('--headless')
        options.add_argument('--disable-gpu')
        driver = webdriver.Chrome(chrome_options=options)
        if self.token and self.driver:
            return

        self.driver = get_web_driver(email, password)
        self.token = self.get_token()

```

But it still launches a Chrome instance for me.

**Comment by SterlingButters** [comment]
Just to be sure, you saved the file after making the changes and running correct?

**Comment by SterlingButters** [comment]
Also what system are you running? I wonder if that has anything to do with it
