### ISSUE TITLE
Is there a plan to support Credit Score?

### ISSUE THREAD

**Issue by marceloramires** [mrooney/mintapi#142]
Mint.com presents your credit score, if you've set it up.

Is there a plan for supporting credit score on this API? 

I would volunteer to do it myself, just wanted to check before doing anything.

**Comment by mrooney** [comment]
I would certainly be happy to review a pull request to add this, thanks! You'd just want to make sure to add a command-line flag as well and document it in the readme :)

**Comment by mrooney** [comment]
This exists in 1.36 and full credit report in 1.37!
