### ISSUE TITLE
Run selenium headless?

### ISSUE THREAD

**Issue by talonmeyer** [mrooney/mintapi#145]
Great API, I'm glad somebody took the time to build this.

Using mintapi from powershell either cmd.exe on Windows 10 and Windows Server 2016. A new Chrome window is opened when I execute the command. This works when I'm logged in with RDP, but running the command from Task Scheduler or as a SQL Server Agent Job will cause it to hang because there is no user interface connected.

How can I adjust it to run selenium headless from the command line?

**Comment by talonmeyer** [comment]
Nice! Did this cut down on resource overhead as well?

**Comment by etiam** [comment]
I didn't run a before/after test but I wouldn't be surprised if headless used less resources.

**Comment by mrooney** [comment]
Headless is now an option with #150, including MFA support.
