### ISSUE TITLE
Can this be executed with headless chrome driver?

### ISSUE THREAD

**Issue by eschizoid** [mrooney/mintapi#149]

**Comment by eschizoid** [comment]
Something like that probably?
https://github.com/eschizoid/mintapi/pull/1/files

**Comment by eschizoid** [comment]
@mrooney Let me know if you like the idea and if you see some value (I can make a real PR)

**Comment by TimothyBramlett** [comment]
@mrooney @eschizoid This is great!  Definitely would be better with the option to run headless! :)

**Comment by eschizoid** [comment]
@TimothyBramlett The PR is ready, just waiting for @mrooney feedback.

**Comment by eschizoid** [comment]
@TimothyBramlett https://github.com/mrooney/mintapi/pull/150

**Comment by mrooney** [comment]
Yes it would either be handled in #150 or #135.
