### ISSUE TITLE
Mint sync apparently incomplete after 5 minutes

### ISSUE THREAD

**Issue by felciano** [mrooney/mintapi#154]
Hello all --

I just did a fresh install of v1.30 and am testing out the new chromium-based functionality. The logging in appears to work correctly, including mfa when needed, but the operation always times out after 5 minutes, yielding this warning:

    UserWarning: Mint sync apparently incomplete after 5 minutes. Data retrieved may not be current.

I'm running via `pipenv`, in case it matters:

    pipenv run mintapi --keyring $(cat /.mintusername) --transactions --filename temp.csv

Is there a debug or verbose flag somewhere that could shed some additional insight?

**Comment by felciano** [comment]
Looks like this may just have been a slowness problem on the Mint side. Today the same command works, with noticeably snappier performance visible in the selenium browser window. I'm going to close this out for the immediate issue, but might be useful to make the timeout configurable or provide some additional logging options at some point (non-urgent I think).

**Comment by mrooney** [comment]
Thanks for the update!
