### ISSUE TITLE
AttributeError: type object 'Mint' has no attribute 'parse_float'

### ISSUE THREAD

**Issue by salmoni88** [mrooney/mintapi#157]
It appears as if parse_float is no longer part of the Mint object.  Looks like it is now part of the api.

I am using mintapi 1.32.  

```
# Get account details in an attempt to get account amounts month over month
account_info = mint.get_accounts(get_detail=True)
```

> Traceback (most recent call last):
>   File "<input>", line 2, in <module>
>   File "/Users/salmoni/PycharmProjects/mint/venv/lib/python2.7/site-packages/mintapi/api.py", line 322, in get_accounts
>     accounts = self.populate_extended_account_detail(accounts)
>   File "/Users/salmoni/PycharmProjects/mint/venv/lib/python2.7/site-packages/mintapi/api.py", line 519, in populate_extended_account_detail
>     account['availableMoney'] = Mint.parse_float(xml[1]['#text'])
> AttributeError: type object 'Mint' has no attribute 'parse_float'

**Comment by mrooney** [comment]
Thanks, should be fixed in the newly released 1.33!
