### ISSUE TITLE
Net Worth?

### ISSUE THREAD

**Issue by elijahchancey** [mrooney/mintapi#16]
How hard would it be to add a function that grabs your net worth (All Assets, including investments minus All Debts)? Ps Thanks for your hard work!

**Comment by mplewis** [comment]
I noticed the same thing as @kunalbhat. Here are the account types I have in my Mint account and their "value types".

**Regular**: positive value = assets, negative value = debt
**Inverse**: positive value = debt, negative value = assets

Account type | Value type
--------- | ----------------------
`credit` | Regular
`loan` | Inverse
`bank` | Regular
`investment` | ??
`vehicle` | Regular

**Comment by elijahchancey** [comment]
This is a great help. Thanks!
