### ISSUE TITLE
anyone else being bombarded with 2FA MFA code requests in headless mode?

### ISSUE THREAD

**Issue by jorythompson** [mrooney/mintapi#176]
Whenever I run my app with the Chromedriver in headless mode, Mint ALWAYS asks for my security code SEVERAL times!
On the other hand, when it runs with the GUI, I don't get the requests.

Any suggestions?

**Comment by mrooney** [comment]
I haven't experienced that. Are you using a recent version, which has the session argument? You don't need to use it explicitly, but this version keeps a Chrome session so this shouldn't happen.

**Comment by jorythompson** [comment]
This happens when I first connect and only in headless mode. Wouldn't the
session argument affect both GUI and headless modes the same way?

**Comment by jorythompson** [comment]
BTW, I see that we should be passing "options" instead of "chrome_options" to chromedriver (it is being deprecated)

**Comment by jorythompson** [comment]
So it may be obvious, but you need to match the version of chromedriver to the version you are using.  I am using chrome 74.0.3729.157 (the current 64 bit windows version) but I tried to use a more recent version that did not work.  I am now using chromedriver version 74.0.3729.6. 

Now, ONLY in headless mode, I am getting:
'unknown error: DevToolsActivePort file doesn\'t exist
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.17763 x86_64)'

This is a known chromedriver bug and supposedly can be temporarily fixed by setting:
chrome_options.add_argument("disable-dev-shm-usage")
This did not work for me.
So headless is not working but the GUI version is (pretty much the same as I originally reported)

**Comment by TimothyBramlett** [comment]
@jorythompson @mrooney I always get 2FA requests every single time I use it now.  Regardless of whether I am using Chrome Headless or running it with a visible chrome window.  Any ideas?

**Comment by jorythompson** [comment]
If you set the session_path this will go away (at least in non headless mode). I believe it persists the cookies so mint doesn't have to reauthorize.

**Comment by jorythompson** [comment]
If you set the session_path this will go away (at least in non headless mode). I believe it persists the cookies so mint doesn't have to reauthorize.

**Comment by TimothyBramlett** [comment]
@jorythompson Okay I will try this tomorrow and let you know if it solves my issue.
