### ISSUE TITLE
Session has expired error

### ISSUE THREAD

**Issue by ghost** [mrooney/mintapi#18]
I am getting the following exception.  Ideas?

Exception: Could not parse account data: <error><code>1</code><description>Session has expired.</description><name></name><type></type></error>

**Comment by brianmxwll** [comment]
Apologies for the issue necro, but is there a common method around this? I can get in very sporadically (1 in 20) but the remainder throw the error at the top of this thread. I suppose looping in a try/catch might be a thing... but that seems grey on the ethical scale and somewhat likely to bring down a hammer.

**Comment by mrooney** [comment]
Hey there Brian, are you experiencing this on the latest master / mintapi 1.17? If so, please feel free to open a new issue, as this specific one was resolved :)
