### ISSUE TITLE
number of transactions returned

### ISSUE THREAD

**Issue by jorythompson** [mrooney/mintapi#183]
I'm only seeing a handful of transactions when calling get_transactions_json().  I was hoping to get a months worth of transactions.  I tried changing "cash" to "all" and got more, but still nowhere near what I expected.  I know this is not a mintapi problem per se... did Mint change something on their end?

**Comment by jorythompson** [comment]
I think I found the issue - I *thought* I was specifying the correct date (30 days earlier than today) but I was mistaken.

**Comment by mrooney** [comment]
Glad you figured it out!
