### ISSUE TITLE
Log In changed to Sign in

### ISSUE THREAD

**Issue by kennyrowe** [mrooney/mintapi#185]
Looks like mint has changed the wording for logging in. I updated line `221` from `api.py` and that seemed to work. 

```
element = driver.find_element_by_xpath("//a[@aria-label='Sign in']")
```
I trageted the xpath because the archor text has a bunch of crazy white space.

**Comment by tsdg112** [comment]
This works for me.  Thank you.

**Comment by zosky** [comment]
yup - same - was about to do the same - thanks for confirming i was on the right track

**Comment by mrooney** [comment]
Thanks, fixed!
