### ISSUE TITLE
Session_Path & MFA

### ISSUE THREAD

**Issue by flyingfalafel** [mrooney/mintapi#195]
Hi! I'm fairly new to coding - what do I replace 'None' with for the session_path and mfa_input_callback parameters?

All else works great, just the automatic authentication can't complete without these elements. 

Thanks!

**Comment by jaron-l** [comment]
For session_path, as the README.md states:
```
# Directory that the Chrome persistent session will be written/read from.
# To avoid the 2FA code being asked for multiple times, you can either set
# this parameter or log in by hand in Chrome under the same user this runs
# as.
```
If you don't know where that is, [look at this link](https://chromium.googlesource.com/chromium/src/+/master/docs/user_data_dir.md).

As for mfa_input_callback, are you using the "soft-token" mfa-method? I believe that is the only time it is used. If you aren't, leave it as None. If you are, you'll have to write a function that get's that key value for you.

**Comment by mrooney** [comment]
Thanks! Closing as this doesn't seem like a bug, but please correct me if I'm wrong :)
