### ISSUE TITLE
Transaction ID changes when the transaction moves from pending to complete

### ISSUE THREAD

**Issue by josephk77** [mrooney/mintapi#196]
When I query for transactions, (.get_detailed_transactions), I am able to see both pending and completed transactions. If i run the same query a few days later, the pending transactions from the previous query are now completed, but they have different transaction ids. Therefore the newly completed transactions show up as duplicates as I only want to see the new transactions since the last time i ran the query.

Is there anyway to track queries that were previously pending, that are now complete? For example, be able to provide the completed transaction ID with it previous pending transaction ID?

Currently, I have to manually associate a completed transaction with its prior pending transaction

**Comment by mrooney** [comment]
I would guess this is a limitation in the underlying Mint data and may be a limitation with the accounts themselves (the banks may represent these as different transactions to Mint). I'm not aware of any way to do this. Could you simply ignore pending transactions in your queries as they are not complete or final yet?
