### ISSUE TITLE
Add ability to use chromedriver in PATH

### ISSUE THREAD

**Issue by jaron-l** [mrooney/mintapi#201]
The current [get_web_driver](https://github.com/mrooney/mintapi/blob/4bf3f6fe6b90005b4e2b0b63c690786b869bfc4d/mintapi/api.py#L188-L216)  function doesn't check the PATH to see if chromedriver is there. It only checks the current working directory for chromedriver and then attempts to download chromedriver version 2.41 to be used.

It would be easy for me to submit a pull request to check for chromedriver in path and the current directory but I think this is related to a similar issue:

I think it should be considered whether the app should be attempting to get chromedriver for the user at all. I'm not sure if this is causing other issues but if the app will only use version 2.41 of chromedriver published in 2018, then it may cause issues in the future. To me, several of the comments in #95 seem to suggest issues with the chromedriver version not working and none of them seem to have ever been resolved except for the one post where he says he manually put in the path to his chromedriver. The easy way out would be to require the user to provide the chromedriver in PATH or in the current directory.

For documentation purposes, I briefly researched how hard a more robust method might be to automatically find the correct chromedriver version. It would probably require a operating system check and then either run [this command in linux](https://serverfault.com/a/646402) or [a command referenced here in windows](https://bugs.chromium.org/p/chromium/issues/detail?id=158372#c15) that would determine what chrome/chromium version is installed and then download the proper chromedriver according to [these instructions](https://sites.google.com/a/chromium.org/chromedriver/downloads/version-selection). I know that's a lot but if it seems like a good direction to go in, I could submit a pull request.

**Comment by jprouty** [comment]
Wow, crazy coincidence, I was going to open an issue right this second around a similar issue. I would suggest moving to the chromedriver-py package, which will allow users to selectively upgrade/downgrade the exact version as they please, and will make distribution/caching of versions easier.

I'm going to send a pull request over to get the ball going.

**Comment by jprouty** [comment]
For context, the main _driver_ for me, is that I have users of my project (jprouty/mint-amazon-tagger) that are occasionally running into issues ([issue44](https://github.com/jprouty/mint-amazon-tagger/issues/44)) that appear to be version compat issues.

**Comment by mrooney** [comment]
Thanks, I'll close in favor of #202
