### ISSUE TITLE
Mint requires constant verification of some accounts

### ISSUE THREAD

**Issue by jorythompson** [mrooney/mintapi#207]
Every single time I log in to mint (manually or by the api) I am bombarded with requests by mint to verify my connection with various accounts.
Is anyone else having this issue? It almost makes mint useless as it takes so much time to verify each one (I had 20 yesterday!)

**Comment by jorythompson** [comment]
I just got off chat with their "help" desk.  What a waste of time.  I am about ready to drop mint and find an alternative

**Comment by mrooney** [comment]
I haven't noticed this, but I do know Personal Capital is another popular one, with a different backend that folks seem to consider more reliable. Of course, not compatible with Mintapi, but info in case it helps :)

**Comment by jorythompson** [comment]
Do you use 2FA (other than SMS) on any of your accounts?

**Comment by mrooney** [comment]
Ideally there would be an option for authorized APIs to skip 2FA, especially if they are read-only, but without this, it does make sense that when you add extra security factors to your account, they are respected. If this is for accounts with 2FA I don't think there's anything Mintapi can do.

**Comment by jorythompson** [comment]
I realize that this is not a mintapi issue, I was just wondering if anyone
else had similar issues.

**Comment by chino** [comment]
They are moving to OAUTH I believe with many of the accounts. I think it's mostly the backend institutions that are slowly joining the fold.
