### ISSUE TITLE
Any way to get this to work on shared hosting server?

### ISSUE THREAD

**Issue by dzg** [mrooney/mintapi#210]
I would love to be able to run this on a shared hosting server. But AFAIK you need sudo privileges to install selenium.

Maybe with GhostDriver or PhantomJS?

**Comment by jaron-l** [comment]
Do you have docker on your server? I run mine from a docker container and it works great.

**Comment by mrooney** [comment]
I'll close this as it should be possible with Docker. Thanks for the question and answer!
