### ISSUE TITLE
transactions?

### ISSUE THREAD

**Issue by lalskdjdjf** [mrooney/mintapi#22]
How can I download transactions?

**Comment by nikkobautista** [comment]
You should be able to download transactions by hitting the endpoint https://wwws.mint.com/getJsonData.xevent?task=transactions after the `login_and_get_token` method

**Comment by felciano** [comment]
+1

**Comment by mrooney** [comment]
There are two pull requests adding this in different ways, I'll try to merge one in ASAP!

**Comment by felciano** [comment]
Thanks @mrooney that would be awesome!

**Comment by mrooney** [comment]
https://github.com/mrooney/mintapi/pull/28 implemented this and has been merged and released as version 1.6. Let me know if it meets your requirements!
