### ISSUE TITLE
Feature request: Pin chrome driver version

### ISSUE THREAD

**Issue by nickodell** [mrooney/mintapi#230]
I use mintapi on a Debian headless server, using the system's version of Chrome. Occasionally, the chromedriver version within mintapi will update, but the system-provided version won't. That produces an error like this:

```
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 86
Current browser version is 85.0.4183.83 with binary path /usr/bin/google-chrome
```

This is pretty annoying. Recently, I figured out a workaround by editing api.py, and changing this line:

```
CHROME_DRIVER_LATEST_RELEASE = 'LATEST_RELEASE'
```

to

```
CHROME_DRIVER_LATEST_RELEASE = 'LATEST_RELEASE_85'
```

It would be nice to have an official API that doesn't require modifying the library, though. The API would allow me to specify a major version of chromedriver, and mintapi would do its best to get that version.

**Comment by mrooney** [comment]
Have you tried `--use-chromedriver-on-path`?

**Comment by nickodell** [comment]
No, I'll try that.

---

Notes on trying this:

I changed the mintapi call to this:

```py
mint = mintapi.Mint(
    ...,
    headless=True,
    use_chromedriver_on_path=True,
)
```

Then I added the chromedriver to the PATH:

```sh
export PATH="$PATH:/home/njodell/mint"
```

(I added this in the shell script which runs the python script above.)

---

It now works. Thanks! I'm going to close this issue, but feel free to point anyone else to this issue if they run into a similar problem.

**Comment by dcastillo84** [comment]
@nickodell I am having the same issue with a windows machine. How do you find the current path to the chromedriver mintapi is using?

**Comment by nickodell** [comment]
@dcastillo84 mintapi downloads the chromedriver to the current working directory. So you would run mintapi normally to download the chromedriver, then add the current directory to the path, then run mintapi with the `--use-chromedriver-on-path` option, as mrooney suggests above.

Here's how to add the current directory to the path on Window: https://superuser.com/questions/975605/add-current-directory-to-path/975613

Let me know if you have other questions!

**Comment by dcastillo84** [comment]
You are awesome! Appreciate it. Weird it was putting the chromedriver in my C:\users\username\ folder
