### ISSUE TITLE
ElementNotInteractableException during MFA

### ISSUE THREAD

**Issue by davidacarroll** [mrooney/mintapi#232]
Hello,

Love this repo. I created my own app for scraping the Mint web page and have been using it for a year or so on my Windows machine. Then I ran into this problem while trying to get it working on a raspberry pi 4. And now I am seeing it on both my windows and RPi machines. I've not touched the code on the Windows machine so I'm wondering if something changed at Mint.com.

I am using SMS to authenticate. In the code below, by this point, it has logged in with my credentials and Mint.com has texted me the MFA code. 

Inside api.py: get_web_driver: 

            else:
                driver.find_element_by_id('ius-mfa-options-form')
                driver.implicitly_wait(10)  # seconds [Note: I added this with no effect ]
                try:
                    mfa_method_option = driver.find_element_by_id('ius-mfa-option-{}'.format(mfa_method))
                    driver.implicitly_wait(10)  # seconds [Note: I added this with no effect ]
                    mfa_method_option.click()
 
I have verified that mfa_method == sms so it is trying to find the ius-mfa-option-sms element, and seems to have found it successfully. But when the click is applied on the last line above, it takes an ElementNotInteractableException. I looked this exception up and saw suggestions about putting in some delay to allow the page to load, so I added a driver.implicitly_wait(10) but no help. 

Here is the version information for the Pi OS, chrome driver, chrome browser, and mintapi. 

pi@raspberrypi:~ $ cat /usr/lib/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"

pi@raspberrypi:~ $ apt list chromium-driver
Listing... Done
chromium-driver/stable 83.0.4103.116-1~deb10u2 armhf

pi@raspberrypi:~ $ apt list chromium-browser
Listing... Done
chromium-browser/testing,now 84.0.4147.105-rpt2 armhf [installed,automatic]

pi@raspberrypi:~ $ pip show mintapi
Name: mintapi
Version: 1.44

Thanks for any help! Regards,

**Comment by jaron-l** [comment]
I am able to reproduce this. Looks like Mint.com changed the sign in process. This affects more than just the mfa workflow but occasionally the username and password inputs are on separate pages as well (which workflow I get appears to be random as I'm able to get both at roughly a 50/50 chance with no saved user session). 

I'll have a merge request in just a little bit to fix it.

**Comment by davidacarroll** [comment]
Thanks, Jaron, I'm happy to hear that you were able to reproduce this and submit a PR. I assume once this gets merged into the master that a new mintapi package would be released. How does one follow a PR through this process and become aware of the new package release? Regards,

Dave

**Comment by jaron-l** [comment]
You can easily subscribe to the PR by clicking the subscribe button in the right-hand column when viewing the pull request. This project doesn't have automated builds or use the GitHub release system so I don't know of a way to get notified of new releases. If you want to use this new request sooner, you could just install my fork but realize that it may or may not be as clean/stable as this repo because it hasn't gone through code review, but it works.
