### ISSUE TITLE
Read-Only vs Read/Write API

### ISSUE THREAD

**Issue by MDrock116** [mrooney/mintapi#238]
Is there a reason this API will only read and not update data on Mint?  I'm looking for an API that can update Mint transactions.

**Comment by mrooney** [comment]
This is probably not the API for you, unless you send along a PR for it! :)

**Comment by MDrock116** [comment]
thanks mrooney!  i would be glad to make a PR for that functionality or just add it independently to my app.  I was just wondering if there was a technical or legal blocker that was preventing this functionality to be added as of yet.
