### ISSUE TITLE
login broken > rememberME now default

### ISSUE THREAD

**Issue by zosky** [mrooney/mintapi#244]
hiya. it looks like on monday my CRON job stopped working... 

- if i delete the session-path folder, it works *once*. 
- running **without** --headless, i see remember-me is now default 
- so subsequent runs try "login login" + "pw" ... and fail

i guess this is the purpose of **--session-path None** ?
do let me know if there's something im missing

and most importantly thank you for making this thing !!

**Comment by mrooney** [comment]
Hi there, thanks for the report! I haven't seen any other reports of this, were you able to get it working? IIRC, None is the default session path, but you can set one to have a persistent session, so I'd give that a shot if you haven't already.
