### ISSUE TITLE
Python using CLI Session

### ISSUE THREAD

**Issue by josjaf** [mrooney/mintapi#247]
I'm running this command - ```python mintapi/api.py --keyring --headless you@example.com```

How can I instantiate a Python session using those existing credentials? I'm trying to figure out how often it logs into Mint for new data? For testing, I can use data that's a few days old and doesn't need to be refreshed as i debug my code, but eventually I will want it to refresh the data. I couldn't figure it out by reading the docs. Thanks!

**Comment by mrooney** [comment]
Hi there! I may be misunderstanding, but you run that command each time you want data (with any of the flags for customizing which data you get). It should prompt for a password for the first time, and thereafter it will be in the keyring and won't require a password.
