### ISSUE TITLE
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable

### ISSUE THREAD

**Issue by areagu** [mrooney/mintapi#251]
started getting below issues several days ago: 

selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=89.0.4389.90)

**Comment by nickysemenza** [comment]
There’s some discussion in #250

**Comment by areagu** [comment]
yes thank you - apologies didn't see the issue exists... 
mintapi stopped working as a result several days ago..

**Comment by jasonkissinger** [comment]
this may be same issue that we're also discussing in https://github.com/mrooney/mintapi/issues/248#issuecomment-801633786

check out my pr and see if that works for you.

**Comment by areagu** [comment]
will do - thank you so much!!

**Comment by mrooney** [comment]
Thanks, I'll close this one in favor of #250
