### ISSUE TITLE
mfa/login issues

### ISSUE THREAD

**Issue by clueo8** [mrooney/mintapi#258]
I've been having difficulty lately with getting any type of automated mfa working.  Sometimes the image captcha shows up, and sometimes it doesn't.  I'm trying to use email with a gmail/imap but I don't know if thats possible because of ssl?  Is there anyone who has this working today?

Thanks.

**Comment by nickodell** [comment]
@clueo8 I can describe my setup, which is working so far.

In the mint 2-step verification, you can set an app like Google Authenticator. This will give you two things: a QR code and a "manual setup" code. Scan the QR code with your Google Authenticator app. Copy the manual setup code. This will be all uppercase letters. Pass this as mfa_token. Set your mfa_method to soft-token.

Here's a Python code sample:

```
    mint = mintapi.Mint(
        'me@email.com',
        'my_password',
        mfa_method='soft-token',
        mfa_token='XXXXXXXXX',
    )
```

If you need to log in manually, you will need to use your Google Authenticator app. If mintapi needs to log in, it can use the manual setup code to automatically log in.

**Comment by dcastillo84** [comment]
@nickodell Can you share how you get past the email notifications. I was able to get the authenticator working however its also asking for an email code prior to that and I don't know how to turn that off or bypass it within the mintapi

**Comment by dcastillo84** [comment]
@nickodell that helped a ton thanks for the walkthrough
