### ISSUE TITLE
Return accountId with transactions

### ISSUE THREAD

**Issue by Sarke** [mrooney/mintapi#269]
What is the best way to get the transactions, but also include the `accountId` for each?  I would rather not depend on the `accountName` as it can change (and maybe be duplicate?).

**Comment by mrooney** [comment]
Hi Peter, thanks for using mintapi! For general questions please head to our Discord linked on the README :)

**Comment by Sarke** [comment]
Hi @mrooney, I think I was a bit too indirect since I was not asking for technical help.

Currently it doesn't return the `accountId`.  I would like it to.  This is a feature request.

I realize the Mint API doesn't return this by default.  I think this could be added if only a single account's transactions are fetched, or using a flag to first call the accounts and have the code manually match up the accounts to transactions as it outputs the JSON.

Thanks.
