### ISSUE TITLE
Change linter to pycodestyle

### ISSUE THREAD

**Issue by jaron-l** [mrooney/mintapi#324]
I want to recommend that we switch from flake8 as our linter to [pycodestyle](https://pypi.org/project/pycodestyle/) as it supports automatic correction through [autopep8](https://pypi.org/project/autopep8/). Automatic correction reduces linting overhead as if the style can be applied automatically then the developer doesn't have to worry about it. So far, only pycodestyle/autopep8 and [black](https://pypi.org/project/black/) support auto-correction of python linting problems.

**Comment by mrooney** [comment]
Nice, thanks so much for testing! I checked out both and I definitely am a fan of the black-produced syntax, and like the idea of it having stronger opinions. If you found them both equally easy to work with, I'd say let's go with black.

Do we add it as a check and require people to run it locally, or is there an easy way to integrate w/ Github such that it auto-commits the changes for each PR commit?

**Comment by burkematthew** [comment]
I don't have much experience here, so very little to add.  However, I did notice that black is still in Beta.  Not that that is a deterrent, but I just wanted to make sure that that's clear.

**Comment by mrooney** [comment]
Good reminder! I'm fine with that, I worked in another project with it and enjoyed it :) @jaron-l , if you have any time to send over a Black PR I'd love to review!

**Comment by jaron-l** [comment]
I'll get to this soon.

On Thu, Nov 4, 2021 at 7:17 PM Michael Rooney 'notifications at github.com'
<jaron-github+reply+ADGNKUGVF33VBZRMH3VPS3F7SBTTVEVBNHHD3RK4EE=

**Comment by jaron-l** [comment]
In my attempt to create a pull request for this, I noticed that black did indeed break our code. The only example that was caught by tests was it removed the return statement from Mint::get_transactions.

I can easily fix it but perhaps this shows black is still in beta and maybe we should perhaps reconsider using autopep8? I can see both sides:
Pro for autopep8 is that because it is less aggressive, it is more stable and less likely to break code
Pro for black is that in nominal conditions, the only code it will be formatting in PRs in the PR specific code, which if we have a test standard for, will unlikely get broken due to black.
