### ISSUE TITLE
import of keyring should be lazy

### ISSUE THREAD

**Issue by ericbuehl** [mrooney/mintapi#35]
Keyring doesn't work on some platforms (notably AppEngine).  This could be fixed by lazy loading it in main() but it is still listed as a required package in setup.py.  Should it still be a strict requirement?

**Comment by mark-adams** [comment]
I just submitted a PR that proposes a similar change.

My PR only imports the `keyring` package if the `--keyring` argument is given. If the `--keyring` argument is given and `keyring` fails to import, an error will be given. If the `--keyring` argument is not given, `keyring` will not be imported and everything should work fine.

**Comment by mrooney** [comment]
Thanks, I'll close this since we have a PR!

**Comment by mrooney** [comment]
Thanks, released to pypi as 1.9!
