### ISSUE TITLE
get_transactions python 3 compatibility

### ISSUE THREAD

**Issue by APTy** [mrooney/mintapi#45]
Hey I noticed that PR https://github.com/mrooney/mintapi/pull/42 was merged on May 25 and [mintapi-1.10.1](https://pypi.python.org/pypi/mintapi/1.10.1) was released on the same day. Were the python 3 improvements from that PR intended to be included as part of the `1.10.1` release? When I try downloading it, the updates don't seem to be there.

    $ curl -O https://pypi.python.org/packages/source/m/mintapi/mintapi-1.10.1.tar.gz
    $ tar xvfz mintapi-1.10.1.tar.gz
    $ cat mintapi-1.10.1/mintapi/api.py | grep StringIO

        from StringIO import StringIO
        s = StringIO()

Whereas the most recent commits in the repo would show:

    $ cat mintapi/api.py | grep StringIO

    from StringIO import StringIO  # Python 2
    from io import BytesIO as StringIO  # Python 3
        s = StringIO(result.content)

Would love to have the added functionality in python 3 if possible. Thanks!

**Comment by mrooney** [comment]
Thank you for the heads up, not sure what happened there, this should be fixed in 1.10.2 :)
