### ISSUE TITLE
Net-worth and accounts don't save to output file

### ISSUE THREAD

**Issue by felciano** [mrooney/mintapi#49]
If you try to save either net worth or account listings to a JSON file from the commandline, you end up with an empty (0 byte) file. Looks like at the bottom of api.py:
```
json.dumps(data, f, indent=2)
```
should be
```
json.dump(data, f, indent=2)
```
since only the latter call has built-in support for writing to a file-like object.

**Comment by mrooney** [comment]
Thanks, fixed and released as 1.14 :)

**Comment by felciano** [comment]
+1
