### ISSUE TITLE
JSON pull issue

### ISSUE THREAD

**Issue by dtiz** [mrooney/mintapi#57]
For some reason the JSON pulls are throwing an error with the request_and_check. Not sure why this happens now. It's saying the content type 'application/son;charset=UTF-8' does not match 'text/json'

Going to that site, the data looks fine and seems to be in JSON format.

**Comment by tylerneu** [comment]
I'm assuming the returned Content-Type changed after `get_transactions_json` was added. I have submitted a pull request that simply updates the expected header value.

**Comment by pca2** [comment]
+1

**Comment by mrooney** [comment]
Looks great, thanks, merged and released as 1.17!
