### ISSUE TITLE
Getting SSL3 bad handshake error

### ISSUE THREAD

**Issue by felciano** [mrooney/mintapi#58]
About a week ago I started getting this error when running mintapi from the command line:

```
requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)",)
```
This happens whether it is called from code or commandline. I thought it might be a sporadic SSL issue with Mint but it doesn't seem to be going away. 

I also did a `pip install mintapi --upgrade` which pulled down v1.16 and upgraded to requests 2.9.0. These did not fix the issue

Any thoughts on how to diagnose this further?

**Comment by dmazin** [comment]
What system are you running this on? What version of openssl?

**Comment by felciano** [comment]
Sorry I should have included that in the original bug report.

Running on OSX Mavericks v10.11.2, with OpenSSL 0.9.8zg 14 July 2015.

**Comment by dmazin** [comment]
What if you force downgrade py-certifi? I think this one's old enough: pip
install certifi==2015.04.28

**Comment by felciano** [comment]
Yup, that fixed it. Thanks. Is this related to http://stackoverflow.com/questions/34085552/sslerror-bad-handshake-python-requests?
