### ISSUE TITLE
Mint Shutting Down

### ISSUE THREAD

**Issue by jhmart3** [mrooney/mintapi#622]
Article from Mint:
[https://mint.intuit.com/blog/mint-app-news/intuit-credit-karma-welcomes-minters/](https://mint.intuit.com/blog/mint-app-news/intuit-credit-karma-welcomes-minters/)

Will there be a plan to continue this project with a new budgeting service?

**Comment by mendywoly** [comment]
I use this to get my transaction across all my accounts. Is there any other good alternatives to accomplish this? 

Thank you to all the contributors.

**Comment by mrooney** [comment]
We've got a pinned post in the Discord (https://discord.gg/YjJEuJRAu9) where we are actively discussing options. For something fast moving with a lot of discussion, I think that's going to be the best place :)
