### ISSUE TITLE
Error getting transactions

### ISSUE THREAD

**Issue by mrfiat** [mrooney/mintapi#65]
I cannot get this library to get anything off mint.com.  I am calling it like this:

mintapi -t 'username' 'password'

I get this error when trying to get the transactions:

RuntimeError: Error requesting 'https://wwws.mint.com/transactionDownload.event', content type 'text/html; charset=UTF-8' does not match 'text/csv'

Is this library currently working?

Thanks.

**Comment by mrfiat** [comment]
I first ran into this error on Ubuntu.  I then did a install of Mintapi on Centos 6.7 and got the same error?

**Comment by mrfiat** [comment]
Ok, I solved the problem.  The account I was using at mint.com was an older one that logged in with a username instead of an email address and would not work with mintapi.  I used a different mint.com account and it did work.

**Comment by mrooney** [comment]
This should be fixed in 1.17, as well :)

**Comment by sungchun12** [comment]
Hello,

I'm getting this same error as well even though my credentials are correct

#this works just fine
mint = mintapi.Mint('username','password')

Errors out at this line of code:
mint_data=mint.get_transactions() # as pandas dataframe

RuntimeError: Error requesting 'https://wwws.mint.com/transactionDownload.event', content type 'text/html; charset=UTF-8' does not match 'text/csv'

When I type the link in the browser, it downloads the data manually just fine as csv.

**Comment by linkgan** [comment]
+1 I am having the same issue and getting the same error. Wondering if there's an update. Thanks!

**Comment by mrooney** [comment]
Would this be related to https://github.com/mrooney/mintapi/pull/77?
