### ISSUE TITLE
Is this using the most up-to-date/best data sources?

### ISSUE THREAD

**Issue by mike503** [mrooney/mintapi#67]
I've found multiple datasources and not sure if this is using the best ones, and if there is any tribal knowledge around which ones might stick around longer - it would be sad to invest a lot of effort into reverse engineering datasources that will be deprecated.

There is the "master controller" one - which this project uses for almost everything. I don't like it as much as it requires a more complex POST request, but it does seem to provide the most verbose response:
https://wwws.mint.com/bundledServiceController.xevent
It requires the token and a request ID.

There are these, which are cleaner, but aren't as verbose as the bundledServiceController:
https://wwws.mint.com/getJsonData.xevent?task=tags
https://wwws.mint.com/getJsonData.xevent?task=categories
https://wwws.mint.com/getJsonData.xevent?task=accounts - this doesn't show hidden accounts, but does show current balance which bundledServiceController.xevent doesn't
https://wwws.mint.com/getJsonData.xevent?task=transactions
They all seem to support pagination with "offset" parameter if needed. They don't require the token or request ID, only cookies.

There are these, which seem to need the oauth based authorization before accessing:
https://mint.finance.intuit.com/v1/accounts
https://mint.finance.intuit.com/v1/fis
(maybe more)

Also, is there a particular reason why the login process hits 3 endpoints? It appears that you only need to hit loginUserSubmit.xevent and you get back everything you need (token and cookies) to make any other followup requests.

**Comment by mrooney** [comment]
Thanks Mike for the thoughts! This project has existed for years and has had to evolve as their internal services change, so it isn't necessarily the case that everything was designed for the way the services work now. Feel free to clean up any login code or make any other improvements in a PR if it improves something and I'll happily review :)
