### ISSUE TITLE
Date contains only the month and date but not the year

### ISSUE THREAD

**Issue by vkalokyri** [mrooney/mintapi#69]
When I'm downloading my data, all my date fields are of the form, "Month date", (e.g. Oct 29). However, I wanna get also the year of the date and get something like Oct 29, 2015. Can you fix that please? I guess it's pretty simple.

**Comment by mrooney** [comment]
Thanks for the report! Can you clarify what command line command or API command you are using to get data, as there are many :) For some APIs, Mint doesn't return year data if the year is the current year, and then will start appending years once you get into the past year.
