### ISSUE TITLE
Initiating accounts refresh from the command line

### ISSUE THREAD

**Issue by chrisvanpatten** [mrooney/mintapi#70]
Is it possible to initiate an account refresh from the command line utility? Something like `mintapi --initiate-account-refresh email@address.com password` would be great.

Thanks!

**Comment by mrooney** [comment]
Mint.com automatically triggers a refresh on login if enough time has elapsed, so any command will do this, though it doesn't "wait" for the refresh, so you could do this yourself like `mintapi email password && sleep 30 && mintapi email password`. I suppose we could add an option to wait for the refresh before running the commands! What do you think?

**Comment by chrisvanpatten** [comment]
Ahh, I didn't realise that Mint would automatically refresh the accounts on login, even through the script, but that makes sense in hindsight. I suppose it might be easier to note that in the docs, instead of adding extra code :)

For my particular purposes ([an Amazon Echo Alexa command](https://github.com/chrisvanpatten/alexa-bookkeeper)) a "wait" wouldn't really work, but might be good for others. Instead, I've settled on a cron job-triggered [Python script](https://github.com/chrisvanpatten/alexa-bookkeeper/blob/master/refresh.py) that initiates the account refresh method every few hours so the accounts are up-to-date when they're fully fetched. However, armed with this new knowledge, I could also pretty easily update the cron job to just call the mintapi command instead of going through a Python script :)

**Comment by mrooney** [comment]
Cool, nice Echo command! I'll close this for now then, but feel free to open a PR that better explains this in an intuitive way in the README!
