### ISSUE TITLE
Can the API support write operations?

### ISSUE THREAD

**Issue by felciano** [mrooney/mintapi#71]
Hi --

I've been toying with the idea of automating the creation of Mint splits based on detailed transaction info. For example, Amazon allows you to download a detailed order history, which shows you the different items you purchased in a single order. These appear as a single transaction in Mint labeled "Amazon" and typically marked Shopping. More useful for budgeting and analysis would be to split this into the individual purchased items and categorize accordingly (books, camera gear, computer, etc).

Mint obviously allows you to do this by hand by splitting a transaction and adding the line items for each sub-transaction. I'm wondering whether this operation could also be done via mintapi calls  to push data back to Mint? If so then this is something I'd be interested in contributing as a side project.

Any thoughts?

Ramon

**Comment by boondawgy** [comment]
Very cool idea!

**Comment by mrooney** [comment]
Neat! If you can do it via the web interface, I'd imagine you use their API via mintapi/http do the same thing. Definitely feel free to give it a go as a PR or as a separate project that uses the API :)

**Comment by felciano** [comment]
Got it -- so I assume the api doesn't support write operations today? AFAICT this is essentially using non-documented APIs so I'm into new territory. Any pointers for figuring out the APIs in questions, e.g. by monitoring interaction browser UI use?

**Comment by mrooney** [comment]
Exactly @felciano, Mint has no public / documented API, so you have to use your browser inspector to watch XHR requests and then make similar requests programmatically. The mintapi code base will make it a little easier given that it handles logging in and sessions, but you can borrow that code or implement yourself as well :)

**Comment by ajitpawar** [comment]
+1
FYI, I found this which might help: 
[https://mint.lc.intuit.com/questions/1148619-is-there-mint-api-to-add-old-transactions](https://mint.lc.intuit.com/questions/1148619-is-there-mint-api-to-add-old-transactions)

/updateTransaction.xevent with the following parameters:
amount
cashTxnType
catId
category
date
isInvestment	false
merchant
mtAccount
mtCashSplit
mtCashSplitPref
mtCheckNo
mtIsExpense
mtType
note
symbol
task

**Comment by liorofir** [comment]
+1

**Comment by erturpin** [comment]
@felciano it's amazing, I was searching online and came across @mrooney's project here because I had the same idea as you.

I'm going to attempt to create a python script that leverages mintapi to read from Mint, reads from one or more Amazon accounts, and will try to break things out of the category of "Shopping" for better trend analysis and budgeting.

I'll probably try to do the Mint write requests in such a way that I can contribute back into mintapi via  PR.

For my Amazon script, I'm thinking I'll let the user configure how many weeks/months to look back in Amazon and Mint. Then I'll either show them each item from every Amazon order and let them pick from their Mint categories, or I'll try to guess the category by looking at the product's page on Amazon.

**Comment by tonyxiao** [comment]
what about the mint mobile app? I would imagine it probably exposes a simpler api to interact with?

**Comment by boondawgy** [comment]
Yes it can. I've done updates to existing transactions in my own code. If I
get free time ill clean it up and issue a pull request.

**Comment by mr-fuller** [comment]
Hello,
Has anyone looked into automatically updating manual accounts? I have entered a couple accounts manually because mint doesn't support the accounts at the moment, so I have to update the balances every month. 
Similarly, it might be useful to essentially create recurring manual transactions.

**Comment by dzg** [comment]
I would also like to be able to update manual account balance without having to log in to website. 

Anyone have any progress doing this??

**Comment by dzg** [comment]
Maybe this could help?
https://github.com/dan-v/mint-bitcoin-sync

**Comment by jprouty** [comment]
Hi All!

For those looking to spiffy up their Amazon purchases inside of Mint, I just finished up a script to do just that. Take a look:
https://github.com/jprouty/mint-amazon-tagger

Any feedback is welcome!

**Comment by mrooney** [comment]
I'm going to close this for now as it isn't a bug, and probably out of the scope of this project, but if someone ends up opening a PR I will certainly review and consider it!
