### ISSUE TITLE
Issues with getting transactions

### ISSUE THREAD

**Issue by sungchun12** [mrooney/mintapi#74]
Hello! I'm having issues with getting the transactions into a dataframe. My login seems to work fine, but the below code indicates that the transactions aren't being interpreted as a CSV type file.

How do I fix this?

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-bc8cfb10cbed> in <module>()
      4 # Get transactions
      5 
----> 6 mint_data=mint.get_transactions() # as pandas dataframe
      7 
      8 budgets=mint.get_budgets()

C:\Users\schung013\AppData\Local\Continuum\Anaconda2\lib\site-packages\mintapi\api.pyc in get_transactions(self)
    363         """
    364         assert_pd()
--> 365         s = StringIO(self.get_transactions_csv())
    366         s.seek(0)
    367         df = pd.read_csv(s, parse_dates=['Date'])

C:\Users\schung013\AppData\Local\Continuum\Anaconda2\lib\site-packages\mintapi\api.pyc in get_transactions_csv(self, include_investment)
    335             ('?accountId=0' if include_investment else ''),
    336             headers=self.headers,
--> 337             expected_content_type='text/csv'
    338             )
    339         return result.content

C:\Users\schung013\AppData\Local\Continuum\Anaconda2\lib\site-packages\mintapi\api.pyc in request_and_check(self, url, method, expected_content_type, **kwargs)
    104                 raise RuntimeError(
    105                     'Error requesting %r, content type %r does not match %r' %
--> 106                     (url, content_type, expected_content_type))
    107         return result
    108 

RuntimeError: Error requesting 'https://wwws.mint.com/transactionDownload.event', content type 'text/html; charset=UTF-8' does not match 'text/csv'

**Comment by liorofir** [comment]
having the same issue. may be related to the login issue. what is the content of the return HTML?

**Comment by sungchun12** [comment]
content of the return html? It doesn't show anything. It just shows this error handling code.

**Comment by liorofir** [comment]
I believe the get_transactions_csv call to mint expects a CSV formatted file as the return. Instead it's getting HTML. The HTML could be some sort of login or error message. That's why I believe it's related to the login failure issue. Capturing the content of the retuning HTML could give us a clue to what's happening and whether it's related.

**Comment by liorofir** [comment]
This is the HTML that's returned:

``<head>
	<title id="ACCESS_DENIED_HTML_TITLE">${{PFMName}} | Access Denied</title>
	<meta http-equiv="refresh" content="100;URL=https://wwws.mint.com" id="meta-refresh" />
	<link rel="stylesheet" href="sc/dev000/css/error.css" type="text/css" media="screen" title="mint product css" charset="utf-8" />
</head>

<body id="body-mint">
	<div id="container">
		<a name="top" id="logo-link" href="overview.event"> </a>
		<div id="main">
			<h1>Perhaps you took a wrong turn?</h1>
			<p>Sorry about this! Here are a few things you can try:</p>
			<ul>
				<li><a href="/login.event">Log in again</a></li>
				<li><a href="/overview.event">Go to your overview</a></li>
			</ul>
		</div>
	</div>
</body>``

**Comment by boondawgy** [comment]
My gut says this is related to the login issue.  My suggestion is to
help/wait for the login to be resolved, then revisit this if necessary.

**Comment by sungchun12** [comment]
Hello, yes this is most likely the login issue. Thanks folks! I'll close this now.

**Comment by liorofir** [comment]
the return HTML definitely points to the login issue. Non of the other functions that retrieve mint data should work.
