### ISSUE TITLE
content type 'text/html; charset=UTF-8' does not match 'text/csv'

### ISSUE THREAD

**Issue by ccaseyldc** [mrooney/mintapi#76]
`File "/usr/local/lib/python2.7/site-packages/mintapi/api.py", line 337, in get_transactions_csv
    expected_content_type='text/csv'
  File "/usr/local/lib/python2.7/site-packages/mintapi/api.py", line 106, in request_and_check
    (url, content_type, expected_content_type))
RuntimeError: Error requesting 'https://wwws.mint.com/transactionDownload.event', content type 'text/html; charset=UTF-8' does not match 'text/csv'
`
Using version mintapi-1.18.

**Comment by deeka** [comment]
i am getting the same error

**Comment by jasoncorso** [comment]
This is a symptom of the underlying login issue #73

**Comment by mrooney** [comment]
Thanks @jasoncorso! FWIW, I just merged a PR and updated the README, now has instructions for the relevant cookies!
