### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by jorythompson** [mrooney/mintapi#79]
I found this thread: https://github.com/mrooney/mintapi/issues/73 and found the reference to the ius_session cookie.  I was able to retrieve my ius_session cookie from a new attempt to login on Firefox.  I tried this new cookie like this:
`mint = mintapi.Mint(email=EMAIL, password=PASSWORD, ius_session=IUS_SESSION)
`
but get the following:

```
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.2.3\helpers\pydev\pydevd.py", line 1580, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.2.3\helpers\pydev\pydevd.py", line 964, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "Y:/python development/mint_to_evernote/mint.py", line 5, in <module>
    mint = mintapi.Mint(email=EMAIL, password=PASSWORD, ius_session=IUS_SESSION)
  File "Y:\python development\github\mintapi\api.py", line 60, in __init__
    self.login_and_get_token(email, password, ius_session)
  File "Y:\python development\github\mintapi\api.py", line 146, in login_and_get_token
    response = json.loads(response)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

```

I am running code from origin/master that I just pulled this morning (9/14/2016

**Comment by dyburke** [comment]
Hey.  Thanks for helping with the login issue; we all want to fix that.  Though, I'm not convinced this should be in a separate issue since this is the piece of code that is currently struggling.  Please make this post in #73 so we can have one stream of info for the issue.

As far as your particular error goes, have you looked at the response?  Perhaps it's not JSON at all...  I don't know what's being fed to json.loads() so it's hard to say without that info; I suggest you start there. (And post in #73 for the login issue :)

**Comment by jbms** [comment]
I am getting this same error --- Mint seems to be sending an HTML response rather than a JSON response.

**Comment by jbms** [comment]
This issue is due to the change from wwws.mint.com to mint.intuit.com, as mentioned in #73.  Changing all of the URLs fixes this problem.

**Comment by mrooney** [comment]
Merged a PR and updated the README, now has instructions for the relevant cookies!
