### ISSUE TITLE
mint.get_transactions_json()

### ISSUE THREAD

**Issue by jorythompson** [mrooney/mintapi#80]
Got everything (that I am using so far) working with one exception.  I am trying to limit how far this method reaches back in time.  Here is my code:
`first_of_month = datetime.date.today()
        first_of_month = datetime.datetime.strptime(str(first_of_month.year) + "-" + str(first_of_month.month) + "-1","%Y-%m-%d")
        print "getting transactions from " + str(first_of_month) + "..."
        transactions = mint.get_transactions_json(include_investment=False, skip_duplicates=False,
                                                  start_date=first_of_month)
`
I checked the date and it looks good (1/10/16) but it is pulling transactions from years ago.  Am I doing something wrong?

**Comment by jorythompson** [comment]
Never-mind - I just RTFM and see that it needs to be a string.  Will change and try again when I get a chance...

**Comment by mrooney** [comment]
:)
