### ISSUE TITLE
getting connected account(s) status

### ISSUE THREAD

**Issue by jorythompson** [mrooney/mintapi#81]
1. Is there any way to confirm that mint is able to log into all accounts?  I know it is possible from the web site (you get a warning or error - I don't remember)
2. How about getting upcoming bills?

**Comment by jorythompson** [comment]
1. I found the account information I was looking for (so far)
2. I was able to find the placeholders for "due amount" and "due date" in the account structure but they are always "None" (even for credit types.)  Am I missing something?

**Comment by mrooney** [comment]
Apologies for the delay! Have you tried using the --extended-accounts option?

**Comment by jorythompson** [comment]
And I apologize for not seeing your reply :-)
Maybe I'm missing something: I want to know if Mint is having issues connecting to any institution.  For example, occasionally I will change the password for a bank and forget to update Mint.
From what I see, populate_extended_account_detail() just adds more information about an account (presumably it can already access.)
thanks in advance!

**Comment by mrooney** [comment]
Ah! Good question. You should get json data regardless of when the account was last updated, so it is possible this might include some data about the account/connection status (perhaps with --extended-accounts) but I can't speak to that specifically. If you find it please let me know :)

**Comment by mrooney** [comment]
Closing as the last updated date should allow you to figure out of it hasn't been updated recently.
