### ISSUE TITLE
Challenge/Captcha

### ISSUE THREAD

**Issue by harria3** [mrooney/mintapi#82]
When logging in, I continually get the error: Exception: Challenge required, please log in to Mint.com manually and complete the captcha.
I can log in via a browser, but that session never carries over to the python side.  What is meant by 'log in manually?'

**Comment by boondawgy** [comment]
This is an issue the community hasn't fully solved yet. Are you passing in the ius_session cookie you can obtain from your browser?  If so, simply loading the login page from your browser will refresh your session and the apis will work.

**Comment by harria3** [comment]
Noob here.  How do I pass in the ius_session cookie?  I'm using chrome.  Any hints would be appreciated.

**Comment by bclark00** [comment]
I'm not sure if this is the intended method, but I replaced both of these lines and got it to work:
self.login_and_get_token(email, password, "<ius_session value>")

**Comment by harria3** [comment]
That did it.
For others as inexperienced as me: Found the ius_session by logging into mint, and inspecting the page by right clicking, under Resources -> Cookies -> accounts.intuit.com and pasting that ius_session as stated above.

**Comment by dustball** [comment]
Shouldn't this be in the documentation?

**Comment by dustball** [comment]
Actually, even with mint = mintapi.Mint(u,p,session) it doesn't work, but then again I don't think I'm finding the right "ius" session; I see MINTSESSIONID but nothing like ius_session.

**Comment by mrooney** [comment]
Merged a PR and updated the README, now has instructions for the relevant cookies!

**Comment by dustball** [comment]
Nicely done!
