### ISSUE TITLE
Mobile app API

### ISSUE THREAD

**Issue by tonyxiao** [mrooney/mintapi#85]
Does Mint's mobile app use the same API as its web app? It's possible that the api used on mobile is much simpler / more friendly. (Especially with regard to persisting login credentials, etc).

**Comment by mrooney** [comment]
That's a good question! I'm not really sure this is a bug though. Are you just suggesting to look into how the mobile app works as an alternative approach?

**Comment by tonyxiao** [comment]
yea it's a question, not a bug. Just wondering if you have looked into how Mint's mobile app talks to Mint and whether it's the same as how the webapp talks to mint.
