### ISSUE TITLE
CSV export ignores investment transactions switch

### ISSUE THREAD

**Issue by felciano** [mrooney/mintapi#86]
The `--include-investment` flag does not result in investment transactions returned if the target file is a CSV file. Looks like a simple fix at line 695 of `api.py`:

    elif options.transactions:
        data = mint.get_transactions()

needs to be

    elif options.transactions:
        data = mint.get_transactions(include_investment=options.include_investment)

**Comment by mrooney** [comment]
Thanks for the report, fixed in master! It ended up being only slightly more complicated :) https://github.com/mrooney/mintapi/commit/a6fa2692ae24f528ef3924175c42bb912ec099a7
