### ISSUE TITLE
Auth not working - again?

### ISSUE THREAD

**Issue by nemws1** [mrooney/mintapi#91]
Anybody else having authentication issues - again?  My scripts have been working for a long while, but last night (and still this morning) it stopped working.  I'll double-check my code as well, but just wondering if anybody else is having issues.

**Comment by mrooney** [comment]
It's working as expected for me! Can you clarify what "stopped working" means? What error are you seeing?

**Comment by nemws1** [comment]
I'm getting the following CSS, which looks like it doesn't like my username or password, but I've confirmed they're both correct:

{"CSRFToken":"","clientBuildNumber":"spa95.41","nickname":"","isCreditScoreRegistered":false,"error":{"vError":{"code":2,"isGlobalUser":true,"validatorProperty":"credential","name":"username","copy":"Either your username or password are incorrect.","type":"inline"}},"showMigratePasswordPage":false,"buildNumber":"ph7540.8","supportedLocations":"\/(login|welcome|overview|transaction|bills|planning|goal|trend|creditreport|save|oiiMigration|accountsetup|addprovider|settings|paystub|minttotax|taxcreditscore|taxw2s|minttotaxbrandshake).event"}

I should mention a very important fact - I've taken your code and modified to run it in Perl - I'm most likely a rev behind or something.  My code *was* working up until yesterday, but I'm guessing I'm not doing something that you are doing.

All I needed was confirmation it wasn't a general issue - I'll go look and see if I debug the issue. :)

Thanks so much for this API!!! :)

**Comment by nemws1** [comment]
Yup, I'm missing the thx_guid cookie stuff.  Not sure why my version suddenly stopped working, but I've got some updating to do.

Really wish Mint made this easier... I love the service, but wish the API auth was easier.

**Comment by nemws1** [comment]
And ... I've got it working again. :)
